name: Publish Package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --include=dev
      - run: npm run build
      - run: mv package.json dist
      - run: mv README.md dist
      - run: mv LICENSE dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      - run: npm install --include=dev
      - run: npm run build
      - run: mv package.json dist
      - run: mv README.md dist
      - run: mv LICENSE dist
      - run: cd dist && npm publish --access public
